apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-argo-yml
  namespace: flavius
spec:
  project: default 
  source:
    repoURL: https://github.com/BumbaruFlaviusGabriel/argogolang_ver1.git
    targetRevision: main
    path: argo
  destination:
    server: https://kubernetes.default.svc
    namespace: flavius
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      
